### ISSUE TITLE
Response and Request classes need to be refactored

### ISSUE THREAD

**Issue by chughes741** [chughes741/webserv#46]
`Response` and `Request` should be changed to `HttpResponse` and `HttpRequest` to be more specific.

We should consider giving them `operator<<` overloads to be able to write them to `ofstream`s.

Should they also contain a bare buffer string? That way if they only get a partial message we can come back to it? or maybe just a constructor that returns an error if the message isn't complete.

**Comment by yann1731** [comment]
Talking about that. Should we wrap them inside sessions?

**Comment by chughes741** [comment]
> Talking about that. Should we wrap them inside sessions?

We could have an internal storage for Response/Request in the session, I think we might also want a message queue that we can add to if we need to wait to send things
